/*
 * This source file was generated by the Gradle 'init' task
 */
package advent.of.code;

public class App {

    public static void main(String[] args) throws Exception {

        Day1a day1a = new Day1a();
        Day1b day1b = new Day1b();

        day1a.solve();
        day1b.solve();
    }
}
